// AUTH
export const MODIFY_NAME = 'MODIFY_NAME';
export const MODIFY_PHONE = 'MODIFY_PHONE';
export const MODIFY_EMAIL = 'MODIFY_EMAIL';
export const MODIFY_PASS = 'MODIFY_PASS';
export const USER_CREATED = 'USER_CREATED';
export const USER_NOT_CREATED = 'USER_NOT_CREATED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_NOT_SUCCESS = 'USER_LOGIN_NOT_SUCCESS';
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

// CONTACTS
export const CONTACT_MODIFY_EMAIL = 'CONTACT_MODIFY_EMAIL';
export const CONTACT_SAVE_ERROR = 'CONTACT_SAVE_ERROR';
export const CONTACT_SAVE_SUCCESS = 'CONTACT_SAVE_SUCCESS';
export const CONTACT_SAVE_TRANSFORM = 'CONTACT_SAVE_TRANSFORM';
export const CONTACT_LIST = 'CONTACT_LIST';

// MESSAGES
export const MODIFY_MESSAGE = 'MODIFY_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const USER_TALK_LIST = 'USER_TALK_LIST';
export const USER_TALKS_LIST = 'USER_TALKS_LIST';